@file:Suppress("DEPRECATION")

package tech.thatgravyboat.skyblockpv.dfu.base

import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap
import net.minecraft.core.component.DataComponentPatch
import net.minecraft.core.component.DataComponents
import net.minecraft.nbt.CompoundTag
import net.minecraft.world.item.Item
import net.minecraft.world.item.Items
import net.minecraft.world.level.saveddata.maps.MapId
import tech.thatgravyboat.skyblockpv.SkyBlockPv
import kotlin.jvm.optionals.getOrNull

object BaseItem {

    private val items = Int2ObjectOpenHashMap<Int2ObjectOpenHashMap<Item>>()

    init {
        registerComplex(1, 0, Items.STONE)
        registerComplex(1, 1, Items.GRANITE)
        registerComplex(1, 2, Items.POLISHED_GRANITE)
        registerComplex(1, 3, Items.DIORITE)
        registerComplex(1, 4, Items.POLISHED_DIORITE)
        registerComplex(1, 5, Items.ANDESITE)
        registerComplex(1, 6, Items.POLISHED_ANDESITE)
        registerNormal(2, Items.GRASS_BLOCK)
        registerComplex(3, 0, Items.DIRT)
        registerComplex(3, 1, Items.COARSE_DIRT)
        registerComplex(3, 2, Items.PODZOL)
        registerNormal(4, Items.COBBLESTONE)
        registerComplex(5, 0, Items.OAK_PLANKS)
        registerComplex(5, 1, Items.SPRUCE_PLANKS)
        registerComplex(5, 2, Items.BIRCH_PLANKS)
        registerComplex(5, 3, Items.JUNGLE_PLANKS)
        registerComplex(5, 4, Items.ACACIA_PLANKS)
        registerComplex(5, 5, Items.DARK_OAK_PLANKS)
        registerComplex(6, 0, Items.OAK_SAPLING)
        registerComplex(6, 1, Items.SPRUCE_SAPLING)
        registerComplex(6, 2, Items.BIRCH_SAPLING)
        registerComplex(6, 3, Items.JUNGLE_SAPLING)
        registerComplex(6, 4, Items.ACACIA_SAPLING)
        registerComplex(6, 5, Items.DARK_OAK_SAPLING)
        registerNormal(7, Items.BEDROCK)
        registerNormal(8, Items.WATER_BUCKET)
        registerNormal(9, Items.WATER_BUCKET)
        registerNormal(10, Items.LAVA_BUCKET)
        registerNormal(11, Items.LAVA_BUCKET)
        registerComplex(12, 0, Items.SAND)
        registerComplex(12, 1, Items.RED_SAND)
        registerNormal(13, Items.GRAVEL)
        registerNormal(14, Items.GOLD_ORE)
        registerNormal(15, Items.IRON_ORE)
        registerNormal(16, Items.COAL_ORE)
        registerComplex(17, 0, Items.OAK_LOG)
        registerComplex(17, 1, Items.SPRUCE_LOG)
        registerComplex(17, 2, Items.BIRCH_LOG)
        registerComplex(17, 3, Items.JUNGLE_LOG)
        registerComplex(18, 0, Items.OAK_LEAVES)
        registerComplex(18, 1, Items.SPRUCE_LEAVES)
        registerComplex(18, 2, Items.BIRCH_LEAVES)
        registerComplex(18, 3, Items.JUNGLE_LEAVES)
        registerComplex(19, 0, Items.SPONGE)
        registerComplex(19, 1, Items.WET_SPONGE)
        registerNormal(20, Items.GLASS)
        registerNormal(21, Items.LAPIS_ORE)
        registerNormal(22, Items.LAPIS_BLOCK)
        registerNormal(23, Items.DISPENSER)
        registerComplex(24, 0, Items.SANDSTONE)
        registerComplex(24, 1, Items.CHISELED_SANDSTONE)
        registerComplex(24, 2, Items.CUT_SANDSTONE)
        registerNormal(25, Items.NOTE_BLOCK)
        registerNormal(27, Items.POWERED_RAIL)
        registerNormal(28, Items.DETECTOR_RAIL)
        registerNormal(29, Items.STICKY_PISTON)
        registerNormal(30, Items.COBWEB)
        registerComplex(31, 0, Items.DEAD_BUSH)
        registerComplex(31, 1, Items.SHORT_GRASS)
        registerComplex(31, 2, Items.FERN)
        registerComplex(32, 0, Items.DEAD_BUSH)
        registerNormal(33, Items.PISTON)
        registerNormal(34, Items.PISTON) // piston head
        registerNormal(36, Items.PISTON) // piston extension
        registerComplex(35, 0, Items.WHITE_WOOL)
        registerComplex(35, 1, Items.ORANGE_WOOL)
        registerComplex(35, 2, Items.MAGENTA_WOOL)
        registerComplex(35, 3, Items.LIGHT_BLUE_WOOL)
        registerComplex(35, 4, Items.YELLOW_WOOL)
        registerComplex(35, 5, Items.LIME_WOOL)
        registerComplex(35, 6, Items.PINK_WOOL)
        registerComplex(35, 7, Items.GRAY_WOOL)
        registerComplex(35, 8, Items.LIGHT_GRAY_WOOL)
        registerComplex(35, 9, Items.CYAN_WOOL)
        registerComplex(35, 10, Items.PURPLE_WOOL)
        registerComplex(35, 11, Items.BLUE_WOOL)
        registerComplex(35, 12, Items.BROWN_WOOL)
        registerComplex(35, 13, Items.GREEN_WOOL)
        registerComplex(35, 14, Items.RED_WOOL)
        registerComplex(35, 15, Items.BLACK_WOOL)
        registerNormal(37, Items.DANDELION)
        registerComplex(38, 0, Items.POPPY)
        registerComplex(38, 1, Items.BLUE_ORCHID)
        registerComplex(38, 2, Items.ALLIUM)
        registerComplex(38, 3, Items.AZURE_BLUET)
        registerComplex(38, 4, Items.RED_TULIP)
        registerComplex(38, 5, Items.ORANGE_TULIP)
        registerComplex(38, 6, Items.WHITE_TULIP)
        registerComplex(38, 7, Items.PINK_TULIP)
        registerComplex(38, 8, Items.OXEYE_DAISY)
        registerNormal(39, Items.BROWN_MUSHROOM)
        registerNormal(40, Items.RED_MUSHROOM)
        registerNormal(41, Items.GOLD_BLOCK)
        registerNormal(42, Items.IRON_BLOCK)
        registerNormal(43, Items.STONE_SLAB)
        registerComplex(44, 0, Items.STONE_SLAB)
        registerComplex(44, 1, Items.SANDSTONE_SLAB)
        registerComplex(44, 2, Items.PETRIFIED_OAK_SLAB)
        registerComplex(44, 3, Items.COBBLESTONE_SLAB)
        registerComplex(44, 4, Items.BRICK_SLAB)
        registerComplex(44, 5, Items.STONE_BRICK_SLAB)
        registerComplex(44, 6, Items.NETHER_BRICK_SLAB)
        registerComplex(44, 7, Items.QUARTZ_SLAB)
        registerNormal(45, Items.BRICKS)
        registerNormal(46, Items.TNT)
        registerNormal(47, Items.BOOKSHELF)
        registerNormal(48, Items.MOSSY_COBBLESTONE)
        registerNormal(49, Items.OBSIDIAN)
        registerNormal(50, Items.TORCH)
        registerNormal(51, Items.AIR) // fire
        registerNormal(52, Items.SPAWNER)
        registerNormal(53, Items.OAK_STAIRS)
        registerNormal(54, Items.CHEST)
        registerNormal(55, Items.REDSTONE)
        registerNormal(56, Items.DIAMOND_ORE)
        registerNormal(57, Items.DIAMOND_BLOCK)
        registerNormal(58, Items.CRAFTING_TABLE)
        registerNormal(59, Items.WHEAT)
        registerNormal(60, Items.FARMLAND)
        registerNormal(61, Items.FURNACE)
        registerNormal(62, Items.FURNACE) // lit furnance
        registerNormal(63, Items.OAK_SIGN)
        registerNormal(64, Items.OAK_DOOR)
        registerNormal(65, Items.LADDER)
        registerNormal(66, Items.RAIL)
        registerNormal(67, Items.COBBLESTONE_STAIRS)
        registerNormal(68, Items.OAK_SIGN)
        registerNormal(69, Items.LEVER)
        registerNormal(70, Items.STONE_PRESSURE_PLATE)
        registerNormal(71, Items.IRON_DOOR)
        registerNormal(72, Items.OAK_PRESSURE_PLATE)
        registerNormal(73, Items.REDSTONE_ORE)
        registerNormal(73, Items.REDSTONE_ORE)
        registerNormal(76, Items.REDSTONE_TORCH)
        registerNormal(77, Items.STONE_BUTTON)
        registerNormal(78, Items.SNOW)
        registerNormal(79, Items.ICE)
        registerNormal(80, Items.SNOW_BLOCK)
        registerNormal(81, Items.CACTUS)
        registerNormal(82, Items.CLAY)
        registerNormal(83, Items.SUGAR_CANE)
        registerNormal(84, Items.JUKEBOX)
        registerNormal(85, Items.OAK_FENCE)
        registerNormal(86, Items.CARVED_PUMPKIN)
        registerNormal(87, Items.NETHERRACK)
        registerNormal(88, Items.SOUL_SAND)
        registerNormal(89, Items.GLOWSTONE)
        registerNormal(90, Items.AIR) // portal
        registerNormal(91, Items.JACK_O_LANTERN)
        registerNormal(92, Items.CAKE)
        registerNormal(93, Items.REPEATER)
        registerNormal(94, Items.REPEATER) // powered repeater
        registerComplex(95, 0, Items.WHITE_STAINED_GLASS)
        registerComplex(95, 1, Items.ORANGE_STAINED_GLASS)
        registerComplex(95, 2, Items.MAGENTA_STAINED_GLASS)
        registerComplex(95, 3, Items.LIGHT_BLUE_STAINED_GLASS)
        registerComplex(95, 4, Items.YELLOW_STAINED_GLASS)
        registerComplex(95, 5, Items.LIME_STAINED_GLASS)
        registerComplex(95, 6, Items.PINK_STAINED_GLASS)
        registerComplex(95, 7, Items.GRAY_STAINED_GLASS)
        registerComplex(95, 8, Items.LIGHT_GRAY_STAINED_GLASS)
        registerComplex(95, 9, Items.CYAN_STAINED_GLASS)
        registerComplex(95, 10, Items.PURPLE_STAINED_GLASS)
        registerComplex(95, 11, Items.BLUE_STAINED_GLASS)
        registerComplex(95, 12, Items.BROWN_STAINED_GLASS)
        registerComplex(95, 13, Items.GREEN_STAINED_GLASS)
        registerComplex(95, 14, Items.RED_STAINED_GLASS)
        registerComplex(95, 15, Items.BLACK_STAINED_GLASS)
        registerNormal(96, Items.OAK_TRAPDOOR)
        registerComplex(97, 0, Items.INFESTED_STONE)
        registerComplex(97, 1, Items.INFESTED_COBBLESTONE)
        registerComplex(97, 2, Items.INFESTED_STONE_BRICKS)
        registerComplex(97, 3, Items.INFESTED_MOSSY_STONE_BRICKS)
        registerComplex(97, 4, Items.INFESTED_CRACKED_STONE_BRICKS)
        registerComplex(97, 5, Items.INFESTED_CHISELED_STONE_BRICKS)
        registerComplex(98, 0, Items.STONE_BRICKS)
        registerComplex(98, 1, Items.MOSSY_STONE_BRICKS)
        registerComplex(98, 2, Items.CRACKED_STONE_BRICKS)
        registerComplex(98, 3, Items.CHISELED_STONE_BRICKS)
        registerNormal(99, Items.BROWN_MUSHROOM_BLOCK)
        registerNormal(100, Items.RED_MUSHROOM_BLOCK)
        registerNormal(101, Items.IRON_BARS)
        registerNormal(102, Items.GLASS_PANE)
        registerNormal(103, Items.MELON)
        registerNormal(104, Items.MELON) // melon stem
        registerNormal(105, Items.PUMPKIN) // pumpkin stem
        registerNormal(106, Items.VINE)
        registerNormal(107, Items.OAK_FENCE_GATE)
        registerNormal(108, Items.BRICK_STAIRS)
        registerNormal(109, Items.STONE_BRICK_STAIRS)
        registerNormal(110, Items.MYCELIUM)
        registerNormal(111, Items.LILY_PAD)
        registerNormal(112, Items.NETHER_BRICKS)
        registerNormal(113, Items.NETHER_BRICK_FENCE)
        registerNormal(114, Items.NETHER_BRICK_STAIRS)
        registerNormal(115, Items.NETHER_WART)
        registerNormal(116, Items.ENCHANTING_TABLE)
        registerNormal(117, Items.BREWING_STAND)
        registerNormal(118, Items.CAULDRON)
        registerNormal(119, Items.AIR) // end portal
        registerNormal(120, Items.END_PORTAL_FRAME)
        registerNormal(121, Items.END_STONE)
        registerNormal(122, Items.DRAGON_EGG)
        registerNormal(123, Items.REDSTONE_LAMP)
        registerNormal(124, Items.REDSTONE_LAMP) // lit redstone lamp
        registerNormal(125, Items.OAK_SLAB)
        registerComplex(126, 0, Items.OAK_SLAB)
        registerComplex(126, 1, Items.SPRUCE_SLAB)
        registerComplex(126, 2, Items.BIRCH_SLAB)
        registerComplex(126, 3, Items.JUNGLE_SLAB)
        registerComplex(126, 4, Items.ACACIA_SLAB)
        registerComplex(126, 5, Items.DARK_OAK_SLAB)
        registerNormal(127, Items.COCOA_BEANS)
        registerNormal(128, Items.SANDSTONE_STAIRS)
        registerNormal(129, Items.EMERALD_ORE)
        registerNormal(130, Items.ENDER_CHEST)
        registerNormal(131, Items.TRIPWIRE_HOOK)
        registerNormal(132, Items.STRING) // tripwire
        registerNormal(133, Items.EMERALD_BLOCK)
        registerNormal(134, Items.SPRUCE_STAIRS)
        registerNormal(135, Items.BIRCH_STAIRS)
        registerNormal(136, Items.JUNGLE_STAIRS)
        registerNormal(137, Items.COMMAND_BLOCK)
        registerNormal(138, Items.BEACON)
        registerComplex(139, 0, Items.COBBLESTONE_WALL)
        registerComplex(139, 1, Items.MOSSY_COBBLESTONE_WALL)
        registerNormal(140, Items.FLOWER_POT)
        registerNormal(141, Items.CARROT)
        registerNormal(142, Items.POTATO)
        registerNormal(143, Items.OAK_BUTTON)
        registerComplex(144, 0, Items.SKELETON_SKULL)
        registerComplex(144, 1, Items.WITHER_SKELETON_SKULL)
        registerComplex(144, 2, Items.ZOMBIE_HEAD)
        registerComplex(144, 3, Items.PLAYER_HEAD)
        registerComplex(144, 4, Items.CREEPER_HEAD)
        registerComplex(144, 5, Items.DRAGON_HEAD)
        registerComplex(145, 0, Items.ANVIL)
        registerComplex(145, 1, Items.CHIPPED_ANVIL)
        registerComplex(145, 2, Items.DAMAGED_ANVIL)
        registerNormal(146, Items.TRAPPED_CHEST)
        registerNormal(147, Items.LIGHT_WEIGHTED_PRESSURE_PLATE)
        registerNormal(148, Items.HEAVY_WEIGHTED_PRESSURE_PLATE)
        registerNormal(149, Items.COMPARATOR)
        registerNormal(150, Items.COMPARATOR) // powered comperator
        registerNormal(151, Items.DAYLIGHT_DETECTOR)
        registerNormal(152, Items.REDSTONE_BLOCK)
        registerNormal(153, Items.NETHER_QUARTZ_ORE)
        registerNormal(154, Items.HOPPER)
        registerComplex(155, 0, Items.QUARTZ_BLOCK)
        registerComplex(155, 1, Items.CHISELED_QUARTZ_BLOCK)
        registerComplex(155, 2, Items.QUARTZ_PILLAR)
        registerNormal(156, Items.QUARTZ_STAIRS)
        registerNormal(157, Items.ACTIVATOR_RAIL)
        registerNormal(158, Items.DROPPER)
        registerComplex(159, 0, Items.WHITE_TERRACOTTA)
        registerComplex(159, 1, Items.ORANGE_TERRACOTTA)
        registerComplex(159, 2, Items.MAGENTA_TERRACOTTA)
        registerComplex(159, 3, Items.LIGHT_BLUE_TERRACOTTA)
        registerComplex(159, 4, Items.YELLOW_TERRACOTTA)
        registerComplex(159, 5, Items.LIME_TERRACOTTA)
        registerComplex(159, 6, Items.PINK_TERRACOTTA)
        registerComplex(159, 7, Items.GRAY_TERRACOTTA)
        registerComplex(159, 8, Items.LIGHT_GRAY_TERRACOTTA)
        registerComplex(159, 9, Items.CYAN_TERRACOTTA)
        registerComplex(159, 10, Items.PURPLE_TERRACOTTA)
        registerComplex(159, 11, Items.BLUE_TERRACOTTA)
        registerComplex(159, 12, Items.BROWN_TERRACOTTA)
        registerComplex(159, 13, Items.GREEN_TERRACOTTA)
        registerComplex(159, 14, Items.RED_TERRACOTTA)
        registerComplex(159, 15, Items.BLACK_TERRACOTTA)
        registerComplex(160, 0, Items.WHITE_STAINED_GLASS_PANE)
        registerComplex(160, 1, Items.ORANGE_STAINED_GLASS_PANE)
        registerComplex(160, 2, Items.MAGENTA_STAINED_GLASS_PANE)
        registerComplex(160, 3, Items.LIGHT_BLUE_STAINED_GLASS_PANE)
        registerComplex(160, 4, Items.YELLOW_STAINED_GLASS_PANE)
        registerComplex(160, 5, Items.LIME_STAINED_GLASS_PANE)
        registerComplex(160, 6, Items.PINK_STAINED_GLASS_PANE)
        registerComplex(160, 7, Items.GRAY_STAINED_GLASS_PANE)
        registerComplex(160, 8, Items.LIGHT_GRAY_STAINED_GLASS_PANE)
        registerComplex(160, 9, Items.CYAN_STAINED_GLASS_PANE)
        registerComplex(160, 10, Items.PURPLE_STAINED_GLASS_PANE)
        registerComplex(160, 11, Items.BLUE_STAINED_GLASS_PANE)
        registerComplex(160, 12, Items.BROWN_STAINED_GLASS_PANE)
        registerComplex(160, 13, Items.GREEN_STAINED_GLASS_PANE)
        registerComplex(160, 14, Items.RED_STAINED_GLASS_PANE)
        registerComplex(160, 15, Items.BLACK_STAINED_GLASS_PANE)
        registerComplex(161, 0, Items.ACACIA_LEAVES)
        registerComplex(161, 1, Items.DARK_OAK_LEAVES)
        registerComplex(162, 0, Items.ACACIA_LOG)
        registerComplex(162, 1, Items.DARK_OAK_LOG)
        registerNormal(163, Items.ACACIA_STAIRS)
        registerNormal(164, Items.DARK_OAK_STAIRS)
        registerNormal(165, Items.SLIME_BLOCK)
        registerNormal(166, Items.BARRIER)
        registerNormal(167, Items.IRON_TRAPDOOR)
        registerComplex(168, 0, Items.PRISMARINE)
        registerComplex(168, 1, Items.PRISMARINE_BRICKS)
        registerComplex(168, 2, Items.DARK_PRISMARINE)
        registerNormal(169, Items.SEA_LANTERN)
        registerNormal(170, Items.HAY_BLOCK)
        registerComplex(171, 0, Items.WHITE_CARPET)
        registerComplex(171, 1, Items.ORANGE_CARPET)
        registerComplex(171, 2, Items.MAGENTA_CARPET)
        registerComplex(171, 3, Items.LIGHT_BLUE_CARPET)
        registerComplex(171, 4, Items.YELLOW_CARPET)
        registerComplex(171, 5, Items.LIME_CARPET)
        registerComplex(171, 6, Items.PINK_CARPET)
        registerComplex(171, 7, Items.GRAY_CARPET)
        registerComplex(171, 8, Items.LIGHT_GRAY_CARPET)
        registerComplex(171, 9, Items.CYAN_CARPET)
        registerComplex(171, 10, Items.PURPLE_CARPET)
        registerComplex(171, 11, Items.BLUE_CARPET)
        registerComplex(171, 12, Items.BROWN_CARPET)
        registerComplex(171, 13, Items.GREEN_CARPET)
        registerComplex(171, 14, Items.RED_CARPET)
        registerComplex(171, 15, Items.BLACK_CARPET)
        registerNormal(172, Items.TERRACOTTA)
        registerNormal(173, Items.COAL_BLOCK)
        registerNormal(174, Items.PACKED_ICE)
        registerComplex(175, 0, Items.SUNFLOWER)
        registerComplex(175, 1, Items.LILAC)
        registerComplex(175, 2, Items.TALL_GRASS)
        registerComplex(175, 3, Items.LARGE_FERN)
        registerComplex(175, 4, Items.ROSE_BUSH)
        registerComplex(175, 5, Items.PEONY)
        registerNormal(176, Items.WHITE_BANNER) // standing banner
        registerNormal(177, Items.WHITE_BANNER) // wall banner
        registerNormal(178, Items.DAYLIGHT_DETECTOR)
        registerComplex(179, 0, Items.RED_SANDSTONE)
        registerComplex(179, 1, Items.CHISELED_RED_SANDSTONE)
        registerComplex(179, 2, Items.CUT_RED_SANDSTONE)
        registerNormal(180, Items.RED_SANDSTONE_STAIRS)
        registerComplex(182, 0, Items.RED_SANDSTONE_SLAB)
        registerNormal(183, Items.SPRUCE_FENCE_GATE)
        registerNormal(184, Items.BIRCH_FENCE_GATE)
        registerNormal(185, Items.JUNGLE_FENCE_GATE)
        registerNormal(186, Items.DARK_OAK_FENCE_GATE)
        registerNormal(187, Items.ACACIA_FENCE_GATE)
        registerNormal(188, Items.SPRUCE_FENCE)
        registerNormal(189, Items.BIRCH_FENCE)
        registerNormal(190, Items.JUNGLE_FENCE)
        registerNormal(191, Items.DARK_OAK_FENCE)
        registerNormal(192, Items.ACACIA_FENCE)
        registerNormal(256, Items.IRON_SHOVEL)
        registerNormal(257, Items.IRON_PICKAXE)
        registerNormal(258, Items.IRON_AXE)
        registerNormal(259, Items.FLINT_AND_STEEL)
        registerNormal(260, Items.APPLE)
        registerNormal(261, Items.BOW)
        registerNormal(262, Items.ARROW)
        registerComplex(263, 0, Items.COAL)
        registerComplex(263, 1, Items.CHARCOAL)
        registerNormal(264, Items.DIAMOND)
        registerNormal(265, Items.IRON_INGOT)
        registerNormal(266, Items.GOLD_INGOT)
        registerNormal(267, Items.IRON_SWORD)
        registerNormal(268, Items.WOODEN_SWORD)
        registerNormal(269, Items.WOODEN_SHOVEL)
        registerNormal(270, Items.WOODEN_PICKAXE)
        registerNormal(271, Items.WOODEN_AXE)
        registerNormal(272, Items.STONE_SWORD)
        registerNormal(273, Items.STONE_SHOVEL)
        registerNormal(274, Items.STONE_PICKAXE)
        registerNormal(275, Items.STONE_AXE)
        registerNormal(276, Items.DIAMOND_SWORD)
        registerNormal(277, Items.DIAMOND_SHOVEL)
        registerNormal(278, Items.DIAMOND_PICKAXE)
        registerNormal(279, Items.DIAMOND_AXE)
        registerNormal(280, Items.STICK)
        registerNormal(281, Items.BOWL)
        registerNormal(282, Items.MUSHROOM_STEW)
        registerNormal(283, Items.GOLDEN_SWORD)
        registerNormal(284, Items.GOLDEN_SHOVEL)
        registerNormal(285, Items.GOLDEN_PICKAXE)
        registerNormal(286, Items.GOLDEN_AXE)
        registerNormal(287, Items.STRING)
        registerNormal(288, Items.FEATHER)
        registerNormal(289, Items.GUNPOWDER)
        registerNormal(290, Items.WOODEN_HOE)
        registerNormal(291, Items.STONE_HOE)
        registerNormal(292, Items.IRON_HOE)
        registerNormal(293, Items.DIAMOND_HOE)
        registerNormal(294, Items.GOLDEN_HOE)
        registerNormal(295, Items.WHEAT_SEEDS)
        registerNormal(296, Items.WHEAT)
        registerNormal(297, Items.BREAD)
        registerNormal(298, Items.LEATHER_HELMET)
        registerNormal(299, Items.LEATHER_CHESTPLATE)
        registerNormal(300, Items.LEATHER_LEGGINGS)
        registerNormal(301, Items.LEATHER_BOOTS)
        registerNormal(302, Items.CHAINMAIL_HELMET)
        registerNormal(303, Items.CHAINMAIL_CHESTPLATE)
        registerNormal(304, Items.CHAINMAIL_LEGGINGS)
        registerNormal(305, Items.CHAINMAIL_BOOTS)
        registerNormal(306, Items.IRON_HELMET)
        registerNormal(307, Items.IRON_CHESTPLATE)
        registerNormal(308, Items.IRON_LEGGINGS)
        registerNormal(309, Items.IRON_BOOTS)
        registerNormal(310, Items.DIAMOND_HELMET)
        registerNormal(311, Items.DIAMOND_CHESTPLATE)
        registerNormal(312, Items.DIAMOND_LEGGINGS)
        registerNormal(313, Items.DIAMOND_BOOTS)
        registerNormal(314, Items.GOLDEN_HELMET)
        registerNormal(315, Items.GOLDEN_CHESTPLATE)
        registerNormal(316, Items.GOLDEN_LEGGINGS)
        registerNormal(317, Items.GOLDEN_BOOTS)
        registerNormal(318, Items.FLINT)
        registerNormal(319, Items.PORKCHOP)
        registerNormal(320, Items.COOKED_PORKCHOP)
        registerNormal(321, Items.PAINTING)
        registerComplex(322, 0, Items.GOLDEN_APPLE)
        registerComplex(322, 1, Items.ENCHANTED_GOLDEN_APPLE)
        registerNormal(323, Items.OAK_SIGN)
        registerNormal(324, Items.OAK_DOOR)
        registerNormal(325, Items.BUCKET)
        registerNormal(326, Items.WATER_BUCKET)
        registerNormal(327, Items.LAVA_BUCKET)
        registerNormal(328, Items.MINECART)
        registerNormal(329, Items.SADDLE)
        registerNormal(330, Items.IRON_DOOR)
        registerNormal(331, Items.REDSTONE)
        registerNormal(332, Items.SNOWBALL)
        registerNormal(333, Items.OAK_BOAT)
        registerNormal(334, Items.LEATHER)
        registerNormal(335, Items.MILK_BUCKET)
        registerNormal(336, Items.BRICK)
        registerNormal(337, Items.CLAY_BALL)
        registerNormal(338, Items.SUGAR_CANE)
        registerNormal(339, Items.PAPER)
        registerNormal(340, Items.BOOK)
        registerNormal(341, Items.SLIME_BALL)
        registerNormal(342, Items.CHEST_MINECART)
        registerNormal(343, Items.FURNACE_MINECART)
        registerNormal(344, Items.EGG)
        registerNormal(345, Items.COMPASS)
        registerNormal(346, Items.FISHING_ROD)
        registerNormal(347, Items.CLOCK)
        registerNormal(348, Items.GLOWSTONE_DUST)
        registerComplex(349, 0, Items.COD)
        registerComplex(349, 1, Items.SALMON)
        registerComplex(349, 2, Items.TROPICAL_FISH)
        registerComplex(349, 3, Items.PUFFERFISH)
        registerComplex(350, 0, Items.COOKED_COD)
        registerComplex(350, 1, Items.COOKED_SALMON)
        registerComplex(351, 0, Items.INK_SAC)
        registerComplex(351, 1, Items.RED_DYE)
        registerComplex(351, 2, Items.GREEN_DYE)
        registerComplex(351, 3, Items.COCOA_BEANS)
        registerComplex(351, 4, Items.LAPIS_LAZULI)
        registerComplex(351, 5, Items.PURPLE_DYE)
        registerComplex(351, 6, Items.CYAN_DYE)
        registerComplex(351, 7, Items.LIGHT_GRAY_DYE)
        registerComplex(351, 8, Items.GRAY_DYE)
        registerComplex(351, 9, Items.PINK_DYE)
        registerComplex(351, 10, Items.LIME_DYE)
        registerComplex(351, 11, Items.YELLOW_DYE)
        registerComplex(351, 12, Items.LIGHT_BLUE_DYE)
        registerComplex(351, 13, Items.MAGENTA_DYE)
        registerComplex(351, 14, Items.ORANGE_DYE)
        registerComplex(351, 15, Items.BONE_MEAL)
        registerNormal(352, Items.BONE)
        registerNormal(353, Items.SUGAR)
        registerNormal(354, Items.CAKE)
        registerComplex(26, 0, Items.WHITE_BED)
        registerComplex(26, 1, Items.ORANGE_BED)
        registerComplex(26, 2, Items.MAGENTA_BED)
        registerComplex(26, 3, Items.LIGHT_BLUE_BED)
        registerComplex(26, 4, Items.YELLOW_BED)
        registerComplex(26, 5, Items.LIME_BED)
        registerComplex(26, 6, Items.PINK_BED)
        registerComplex(26, 7, Items.GRAY_BED)
        registerComplex(26, 8, Items.LIGHT_GRAY_BED)
        registerComplex(26, 9, Items.CYAN_BED)
        registerComplex(26, 10, Items.PURPLE_BED)
        registerComplex(26, 11, Items.BLUE_BED)
        registerComplex(26, 12, Items.BROWN_BED)
        registerComplex(26, 13, Items.GREEN_BED)
        registerComplex(26, 14, Items.RED_BED)
        registerComplex(26, 15, Items.BLACK_BED)
        registerComplex(355, 0, Items.WHITE_BED)
        registerComplex(355, 1, Items.ORANGE_BED)
        registerComplex(355, 2, Items.MAGENTA_BED)
        registerComplex(355, 3, Items.LIGHT_BLUE_BED)
        registerComplex(355, 4, Items.YELLOW_BED)
        registerComplex(355, 5, Items.LIME_BED)
        registerComplex(355, 6, Items.PINK_BED)
        registerComplex(355, 7, Items.GRAY_BED)
        registerComplex(355, 8, Items.LIGHT_GRAY_BED)
        registerComplex(355, 9, Items.CYAN_BED)
        registerComplex(355, 10, Items.PURPLE_BED)
        registerComplex(355, 11, Items.BLUE_BED)
        registerComplex(355, 12, Items.BROWN_BED)
        registerComplex(355, 13, Items.GREEN_BED)
        registerComplex(355, 14, Items.RED_BED)
        registerComplex(355, 15, Items.BLACK_BED)
        registerNormal(356, Items.REPEATER)
        registerNormal(357, Items.COOKIE)
        registerNormal(358, Items.FILLED_MAP)
        registerNormal(359, Items.SHEARS)
        registerNormal(360, Items.MELON_SLICE)
        registerNormal(361, Items.PUMPKIN_SEEDS)
        registerNormal(362, Items.MELON_SEEDS)
        registerNormal(363, Items.BEEF)
        registerNormal(364, Items.COOKED_BEEF)
        registerNormal(365, Items.CHICKEN)
        registerNormal(366, Items.COOKED_CHICKEN)
        registerNormal(367, Items.ROTTEN_FLESH)
        registerNormal(368, Items.ENDER_PEARL)
        registerNormal(369, Items.BLAZE_ROD)
        registerNormal(370, Items.GHAST_TEAR)
        registerNormal(371, Items.GOLD_NUGGET)
        registerNormal(372, Items.NETHER_WART)
        registerNormal(373, Items.POTION)
        registerNormal(374, Items.GLASS_BOTTLE)
        registerNormal(375, Items.SPIDER_EYE)
        registerNormal(376, Items.FERMENTED_SPIDER_EYE)
        registerNormal(377, Items.BLAZE_POWDER)
        registerNormal(378, Items.MAGMA_CREAM)
        registerNormal(379, Items.BREWING_STAND)
        registerNormal(380, Items.CAULDRON)
        registerNormal(381, Items.ENDER_EYE)
        registerNormal(382, Items.GLISTERING_MELON_SLICE)

        registerNormal(383, Items.POLAR_BEAR_SPAWN_EGG)
        registerComplex(383, 4, Items.ELDER_GUARDIAN_SPAWN_EGG)
        registerComplex(383, 5, Items.WITHER_SKELETON_SPAWN_EGG)
        registerComplex(383, 6, Items.STRAY_SPAWN_EGG)
        registerComplex(383, 23, Items.HUSK_SPAWN_EGG)
        registerComplex(383, 27, Items.ZOMBIE_VILLAGER_SPAWN_EGG)
        registerComplex(383, 28, Items.SKELETON_HORSE_SPAWN_EGG)
        registerComplex(383, 29, Items.ZOMBIE_HORSE_SPAWN_EGG)
        registerComplex(383, 31, Items.DONKEY_SPAWN_EGG)
        registerComplex(383, 32, Items.MULE_SPAWN_EGG)
        registerComplex(383, 35, Items.VEX_SPAWN_EGG)
        registerComplex(383, 36, Items.VINDICATOR_SPAWN_EGG)
        registerComplex(383, 50, Items.CREEPER_SPAWN_EGG)
        registerComplex(383, 51, Items.SKELETON_SPAWN_EGG)
        registerComplex(383, 52, Items.SPIDER_SPAWN_EGG)
        registerComplex(383, 54, Items.ZOMBIE_SPAWN_EGG)
        registerComplex(383, 55, Items.SLIME_SPAWN_EGG)
        registerComplex(383, 56, Items.GHAST_SPAWN_EGG)
        registerComplex(383, 57, Items.ZOMBIFIED_PIGLIN_SPAWN_EGG)
        registerComplex(383, 58, Items.ENDERMAN_SPAWN_EGG)
        registerComplex(383, 59, Items.CAVE_SPIDER_SPAWN_EGG)
        registerComplex(383, 60, Items.SILVERFISH_SPAWN_EGG)
        registerComplex(383, 61, Items.BLAZE_SPAWN_EGG)
        registerComplex(383, 62, Items.MAGMA_CUBE_SPAWN_EGG)
        registerComplex(383, 63, Items.ENDER_DRAGON_SPAWN_EGG)
        registerComplex(383, 64, Items.WITHER_SPAWN_EGG)
        registerComplex(383, 65, Items.BAT_SPAWN_EGG)
        registerComplex(383, 66, Items.WITCH_SPAWN_EGG)
        registerComplex(383, 67, Items.ENDERMITE_SPAWN_EGG)
        registerComplex(383, 68, Items.GUARDIAN_SPAWN_EGG)
        registerComplex(383, 69, Items.SHULKER_SPAWN_EGG)
        registerComplex(383, 90, Items.PIG_SPAWN_EGG)
        registerComplex(383, 91, Items.SHEEP_SPAWN_EGG)
        registerComplex(383, 92, Items.COW_SPAWN_EGG)
        registerComplex(383, 93, Items.CHICKEN_SPAWN_EGG)
        registerComplex(383, 94, Items.SQUID_SPAWN_EGG)
        registerComplex(383, 95, Items.WOLF_SPAWN_EGG)
        registerComplex(383, 96, Items.MOOSHROOM_SPAWN_EGG)
        registerComplex(383, 97, Items.SNOW_GOLEM_SPAWN_EGG)
        registerComplex(383, 98, Items.OCELOT_SPAWN_EGG)
        registerComplex(383, 99, Items.IRON_GOLEM_SPAWN_EGG)
        registerComplex(383, 100, Items.HORSE_SPAWN_EGG)
        registerComplex(383, 101, Items.RABBIT_SPAWN_EGG)
        registerComplex(383, 102, Items.POLAR_BEAR_SPAWN_EGG)
        registerComplex(383, 103, Items.LLAMA_SPAWN_EGG)
        registerComplex(383, 105, Items.PARROT_SPAWN_EGG)
        registerComplex(383, 120, Items.VILLAGER_SPAWN_EGG)


        registerNormal(384, Items.EXPERIENCE_BOTTLE)
        registerNormal(385, Items.FIRE_CHARGE)
        registerNormal(386, Items.WRITABLE_BOOK)
        registerNormal(387, Items.WRITTEN_BOOK)
        registerNormal(388, Items.EMERALD)
        registerNormal(389, Items.ITEM_FRAME)
        registerNormal(390, Items.FLOWER_POT)
        registerNormal(391, Items.CARROT)
        registerNormal(392, Items.POTATO)
        registerNormal(393, Items.BAKED_POTATO)
        registerNormal(394, Items.POISONOUS_POTATO)
        registerNormal(395, Items.MAP)
        registerNormal(396, Items.GOLDEN_CARROT)
        registerComplex(397, 0, Items.SKELETON_SKULL)
        registerComplex(397, 1, Items.WITHER_SKELETON_SKULL)
        registerComplex(397, 2, Items.ZOMBIE_HEAD)
        registerComplex(397, 3, Items.PLAYER_HEAD)
        registerComplex(397, 4, Items.CREEPER_HEAD)
        registerComplex(397, 5, Items.DRAGON_HEAD)
        registerNormal(398, Items.CARROT_ON_A_STICK)
        registerNormal(399, Items.NETHER_STAR)
        registerNormal(400, Items.PUMPKIN_PIE)
        registerNormal(401, Items.FIREWORK_ROCKET)
        registerNormal(402, Items.FIREWORK_STAR)
        registerNormal(403, Items.ENCHANTED_BOOK)
        registerNormal(404, Items.COMPARATOR)
        registerNormal(405, Items.NETHER_BRICK)
        registerNormal(406, Items.QUARTZ)
        registerNormal(407, Items.TNT_MINECART)
        registerNormal(408, Items.HOPPER_MINECART)
        registerNormal(409, Items.PRISMARINE_SHARD)
        registerNormal(410, Items.PRISMARINE_CRYSTALS)
        registerNormal(411, Items.RABBIT)
        registerNormal(412, Items.COOKED_RABBIT)
        registerNormal(413, Items.RABBIT_STEW)
        registerNormal(414, Items.RABBIT_FOOT)
        registerNormal(415, Items.RABBIT_HIDE)
        registerNormal(416, Items.ARMOR_STAND)
        registerNormal(417, Items.IRON_HORSE_ARMOR)
        registerNormal(418, Items.GOLDEN_HORSE_ARMOR)
        registerNormal(419, Items.DIAMOND_HORSE_ARMOR)
        registerNormal(420, Items.LEAD)
        registerNormal(421, Items.NAME_TAG)
        registerNormal(422, Items.COMMAND_BLOCK_MINECART)
        registerNormal(423, Items.MUTTON)
        registerNormal(424, Items.COOKED_MUTTON)
        registerComplex(425, 15, Items.WHITE_BANNER)
        registerComplex(425, 14, Items.ORANGE_BANNER)
        registerComplex(425, 13, Items.MAGENTA_BANNER)
        registerComplex(425, 12, Items.LIGHT_BLUE_BANNER)
        registerComplex(425, 11, Items.YELLOW_BANNER)
        registerComplex(425, 10, Items.LIME_BANNER)
        registerComplex(425, 9, Items.PINK_BANNER)
        registerComplex(425, 8, Items.GRAY_BANNER)
        registerComplex(425, 7, Items.LIGHT_GRAY_BANNER)
        registerComplex(425, 6, Items.CYAN_BANNER)
        registerComplex(425, 5, Items.PURPLE_BANNER)
        registerComplex(425, 4, Items.BLUE_BANNER)
        registerComplex(425, 3, Items.BROWN_BANNER)
        registerComplex(425, 2, Items.GREEN_BANNER)
        registerComplex(425, 1, Items.RED_BANNER)
        registerComplex(425, 0, Items.BLACK_BANNER)
        registerNormal(427, Items.SPRUCE_DOOR)
        registerNormal(428, Items.BIRCH_DOOR)
        registerNormal(429, Items.JUNGLE_DOOR)
        registerNormal(430, Items.ACACIA_DOOR)
        registerNormal(431, Items.DARK_OAK_DOOR)
        registerNormal(2256, Items.MUSIC_DISC_13)
        registerNormal(2257, Items.MUSIC_DISC_CAT)
        registerNormal(2258, Items.MUSIC_DISC_BLOCKS)
        registerNormal(2259, Items.MUSIC_DISC_CHIRP)
        registerNormal(2260, Items.MUSIC_DISC_FAR)
        registerNormal(2261, Items.MUSIC_DISC_MALL)
        registerNormal(2262, Items.MUSIC_DISC_MELLOHI)
        registerNormal(2263, Items.MUSIC_DISC_STAL)
        registerNormal(2264, Items.MUSIC_DISC_STRAD)
        registerNormal(2265, Items.MUSIC_DISC_WARD)
        registerNormal(2266, Items.MUSIC_DISC_11)
        registerNormal(2267, Items.MUSIC_DISC_WAIT)
    }

    private val damagable = setOf(
        Items.BOW,
        Items.CARROT_ON_A_STICK,
        Items.CHAINMAIL_BOOTS,
        Items.CHAINMAIL_CHESTPLATE,
        Items.CHAINMAIL_HELMET,
        Items.CHAINMAIL_LEGGINGS,
        Items.DIAMOND_AXE,
        Items.DIAMOND_BOOTS,
        Items.DIAMOND_CHESTPLATE,
        Items.DIAMOND_HELMET,
        Items.DIAMOND_HOE,
        Items.DIAMOND_LEGGINGS,
        Items.DIAMOND_PICKAXE,
        Items.DIAMOND_SHOVEL,
        Items.DIAMOND_SWORD,
        Items.ELYTRA,
        Items.FISHING_ROD,
        Items.FLINT_AND_STEEL,
        Items.GOLDEN_AXE,
        Items.GOLDEN_BOOTS,
        Items.GOLDEN_CHESTPLATE,
        Items.GOLDEN_HELMET,
        Items.GOLDEN_HOE,
        Items.GOLDEN_LEGGINGS,
        Items.GOLDEN_PICKAXE,
        Items.GOLDEN_SHOVEL,
        Items.GOLDEN_SWORD,
        Items.IRON_AXE,
        Items.IRON_BOOTS,
        Items.IRON_CHESTPLATE,
        Items.IRON_HELMET,
        Items.IRON_HOE,
        Items.IRON_LEGGINGS,
        Items.IRON_PICKAXE,
        Items.IRON_SHOVEL,
        Items.IRON_SWORD,
        Items.LEATHER_BOOTS,
        Items.LEATHER_CHESTPLATE,
        Items.LEATHER_HELMET,
        Items.LEATHER_LEGGINGS,
        Items.SHEARS,
        Items.SHIELD,
        Items.STONE_AXE,
        Items.STONE_HOE,
        Items.STONE_PICKAXE,
        Items.STONE_SHOVEL,
        Items.STONE_SWORD,
        Items.WOODEN_AXE,
        Items.WOODEN_HOE,
        Items.WOODEN_PICKAXE,
        Items.WOODEN_SHOVEL,
        Items.WOODEN_SWORD,
    )

    private fun registerComplex(id: Int, meta: Int, item: Item) {
        this.items.computeIfAbsent(id) {
            _ -> Int2ObjectOpenHashMap()
        }.put(meta, item)
    }

    private fun registerNormal(id: Int, item: Item) {
        this.items[id] = Int2ObjectOpenHashMap()
        this.items[id].defaultReturnValue(item)
    }

    private val blankEggModel = SkyBlockPv.id("blank_spawn_egg")

    fun getBase(tag: CompoundTag): Triple<Item, Int, DataComponentPatch.Builder>? {
        val id = tag.getIntOr("id", 0)
        val meta = tag.getIntOr("Damage", 0)
        val count = tag.getIntOr("Count", 1)

        val item = this.items[id][meta] ?: return null

        tag.remove("id")
        tag.remove("Damage")
        tag.remove("Count")

        return when {
            item === Items.POTION -> BasePotionItem.getBase(meta, tag.getCompound("tag").getOrNull()).let { (item, contents) ->
                Triple(
                    item,
                    count,
                    DataComponentPatch.builder().set(DataComponents.POTION_CONTENTS, contents)
                )
            }
            item === Items.FILLED_MAP -> Triple(
                item,
                count,
                DataComponentPatch.builder().set(DataComponents.MAP_ID, MapId(meta))
            )
            item in damagable -> Triple(
                item,
                count,
                DataComponentPatch.builder().set(DataComponents.DAMAGE, meta)
            )
            item === Items.POLAR_BEAR_SPAWN_EGG && meta == 0 -> Triple(
                Items.POLAR_BEAR_SPAWN_EGG,
                count,
                DataComponentPatch.builder().set(DataComponents.ITEM_MODEL, blankEggModel)
            )
            else -> Triple(
                item,
                count,
                DataComponentPatch.builder()
            )
        }
    }

}
