name: Misc Questions/Suggestions/Issues
description: Ask anything or suggest new features that are not bugs.
labels: [ bug ]
body:
    -   type: textarea
        id: text
        attributes:
            label: Your Question/Suggestion/Issue
            description: Please describe your question, suggestion, or issue in detail.
            placeholder: Describe it here
        validations:
            required: true
