package tech.thatgravyboat.skyblockpv.dfu.fixes

import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap
import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.nbt.CompoundTag
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.item.Item
import tech.thatgravyboat.skyblockapi.utils.extentions.getIntOrNull

object FlatteningFixer {

    private val MAP = Int2ObjectOpenHashMap<ResourceLocation>().apply {
        registerComplex(1, 0, "stone")
        registerComplex(1, 1, "granite")
        registerComplex(1, 2, "polished_granite")
        registerComplex(1, 3, "diorite")
        registerComplex(1, 4, "polished_diorite")
        registerComplex(1, 5, "andesite")
        registerComplex(1, 6, "polished_andesite")
        registerNormal(2, "grass_block")
        registerComplex(3, 0, "dirt")
        registerComplex(3, 1, "coarse_dirt")
        registerComplex(3, 2, "podzol")
        registerNormal(4, "cobblestone")
        registerComplex(5, 0, "oak_planks")
        registerComplex(5, 1, "spruce_planks")
        registerComplex(5, 2, "birch_planks")
        registerComplex(5, 3, "jungle_planks")
        registerComplex(5, 4, "acacia_planks")
        registerComplex(5, 5, "dark_oak_planks")
        registerComplex(6, 0, "oak_sapling")
        registerComplex(6, 1, "spruce_sapling")
        registerComplex(6, 2, "birch_sapling")
        registerComplex(6, 3, "jungle_sapling")
        registerComplex(6, 4, "acacia_sapling")
        registerComplex(6, 5, "dark_oak_sapling")
        registerNormal(7, "bedrock")
        registerNormal(8, "water_bucket")
        registerNormal(9, "water_bucket")
        registerNormal(10, "lava_bucket")
        registerNormal(11, "lava_bucket")
        registerComplex(12, 0, "sand")
        registerComplex(12, 1, "red_sand")
        registerNormal(13, "gravel")
        registerNormal(14, "gold_ore")
        registerNormal(15, "iron_ore")
        registerNormal(16, "coal_ore")
        registerComplex(17, 0, "oak_log")
        registerComplex(17, 1, "spruce_log")
        registerComplex(17, 2, "birch_log")
        registerComplex(17, 3, "jungle_log")
        registerComplex(18, 0, "oak_leaves")
        registerComplex(18, 1, "spruce_leaves")
        registerComplex(18, 2, "birch_leaves")
        registerComplex(18, 3, "jungle_leaves")
        registerComplex(19, 0, "sponge")
        registerComplex(19, 1, "wet_sponge")
        registerNormal(20, "glass")
        registerNormal(21, "lapis_ore")
        registerNormal(22, "lapis_block")
        registerNormal(23, "dispenser")
        registerComplex(24, 0, "sandstone")
        registerComplex(24, 1, "chiseled_sandstone")
        registerComplex(24, 2, "cut_sandstone")
        registerNormal(25, "note_block")
        registerNormal(27, "powered_rail")
        registerNormal(28, "detector_rail")
        registerNormal(29, "sticky_piston")
        registerNormal(30, "cobweb")
        registerComplex(31, 0, "dead_bush")
        registerComplex(31, 1, "short_grass")
        registerComplex(31, 2, "fern")
        registerComplex(32, 0, "dead_bush")
        registerNormal(33, "piston")
        registerNormal(34, "piston") // piston head
        registerNormal(36, "piston") // piston extension
        registerComplex(35, 0, "white_wool")
        registerComplex(35, 1, "orange_wool")
        registerComplex(35, 2, "magenta_wool")
        registerComplex(35, 3, "light_blue_wool")
        registerComplex(35, 4, "yellow_wool")
        registerComplex(35, 5, "lime_wool")
        registerComplex(35, 6, "pink_wool")
        registerComplex(35, 7, "gray_wool")
        registerComplex(35, 8, "light_gray_wool")
        registerComplex(35, 9, "cyan_wool")
        registerComplex(35, 10, "purple_wool")
        registerComplex(35, 11, "blue_wool")
        registerComplex(35, 12, "brown_wool")
        registerComplex(35, 13, "green_wool")
        registerComplex(35, 14, "red_wool")
        registerComplex(35, 15, "black_wool")
        registerNormal(37, "dandelion")
        registerComplex(38, 0, "poppy")
        registerComplex(38, 1, "blue_orchid")
        registerComplex(38, 2, "allium")
        registerComplex(38, 3, "azure_bluet")
        registerComplex(38, 4, "red_tulip")
        registerComplex(38, 5, "orange_tulip")
        registerComplex(38, 6, "white_tulip")
        registerComplex(38, 7, "pink_tulip")
        registerComplex(38, 8, "oxeye_daisy")
        registerNormal(39, "brown_mushroom")
        registerNormal(40, "red_mushroom")
        registerNormal(41, "gold_block")
        registerNormal(42, "iron_block")
        registerNormal(43, "stone_slab")
        registerComplex(44, 0, "stone_slab")
        registerComplex(44, 1, "sandstone_slab")
        registerComplex(44, 2, "petrified_oak_slab")
        registerComplex(44, 3, "cobblestone_slab")
        registerComplex(44, 4, "brick_slab")
        registerComplex(44, 5, "stone_brick_slab")
        registerComplex(44, 6, "nether_brick_slab")
        registerComplex(44, 7, "quartz_slab")
        registerNormal(45, "bricks")
        registerNormal(46, "tnt")
        registerNormal(47, "bookshelf")
        registerNormal(48, "mossy_cobblestone")
        registerNormal(49, "obsidian")
        registerNormal(50, "torch")
        registerNormal(51, "air") // fire
        registerNormal(52, "spawner")
        registerNormal(53, "oak_stairs")
        registerNormal(54, "chest")
        registerNormal(55, "redstone")
        registerNormal(56, "diamond_ore")
        registerNormal(57, "diamond_block")
        registerNormal(58, "crafting_table")
        registerNormal(59, "wheat")
        registerNormal(60, "farmland")
        registerNormal(61, "furnace")
        registerNormal(62, "furnace") // lit furnance
        registerNormal(63, "oak_sign")
        registerNormal(64, "oak_door")
        registerNormal(65, "ladder")
        registerNormal(66, "rail")
        registerNormal(67, "cobblestone_stairs")
        registerNormal(68, "oak_sign")
        registerNormal(69, "lever")
        registerNormal(70, "stone_pressure_plate")
        registerNormal(71, "iron_door")
        registerNormal(72, "oak_pressure_plate")
        registerNormal(73, "redstone_ore")
        registerNormal(73, "redstone_ore")
        registerNormal(76, "redstone_torch")
        registerNormal(77, "stone_button")
        registerNormal(78, "snow")
        registerNormal(79, "ice")
        registerNormal(80, "snow_block")
        registerNormal(81, "cactus")
        registerNormal(82, "clay")
        registerNormal(83, "sugar_cane")
        registerNormal(84, "jukebox")
        registerNormal(85, "oak_fence")
        registerNormal(86, "carved_pumpkin")
        registerNormal(87, "netherrack")
        registerNormal(88, "soul_sand")
        registerNormal(89, "glowstone")
        registerNormal(90, "air") // portal
        registerNormal(91, "jack_o_lantern")
        registerNormal(92, "cake")
        registerNormal(93, "repeater")
        registerNormal(94, "repeater") // powered repeater
        registerComplex(95, 0, "white_stained_glass")
        registerComplex(95, 1, "orange_stained_glass")
        registerComplex(95, 2, "magenta_stained_glass")
        registerComplex(95, 3, "light_blue_stained_glass")
        registerComplex(95, 4, "yellow_stained_glass")
        registerComplex(95, 5, "lime_stained_glass")
        registerComplex(95, 6, "pink_stained_glass")
        registerComplex(95, 7, "gray_stained_glass")
        registerComplex(95, 8, "light_gray_stained_glass")
        registerComplex(95, 9, "cyan_stained_glass")
        registerComplex(95, 10, "purple_stained_glass")
        registerComplex(95, 11, "blue_stained_glass")
        registerComplex(95, 12, "brown_stained_glass")
        registerComplex(95, 13, "green_stained_glass")
        registerComplex(95, 14, "red_stained_glass")
        registerComplex(95, 15, "black_stained_glass")
        registerNormal(96, "oak_trapdoor")
        registerComplex(97, 0, "infested_stone")
        registerComplex(97, 1, "infested_cobblestone")
        registerComplex(97, 2, "infested_stone_bricks")
        registerComplex(97, 3, "infested_mossy_stone_bricks")
        registerComplex(97, 4, "infested_cracked_stone_bricks")
        registerComplex(97, 5, "infested_chiseled_stone_bricks")
        registerComplex(98, 0, "stone_bricks")
        registerComplex(98, 1, "mossy_stone_bricks")
        registerComplex(98, 2, "cracked_stone_bricks")
        registerComplex(98, 3, "chiseled_stone_bricks")
        registerNormal(99, "brown_mushroom_block")
        registerNormal(100, "red_mushroom_block")
        registerNormal(101, "iron_bars")
        registerNormal(102, "glass_pane")
        registerNormal(103, "melon")
        registerNormal(104, "melon") // melon stem
        registerNormal(105, "pumpkin") // pumpkin stem
        registerNormal(106, "vine")
        registerNormal(107, "oak_fence_gate")
        registerNormal(108, "brick_stairs")
        registerNormal(109, "stone_brick_stairs")
        registerNormal(110, "mycelium")
        registerNormal(111, "lily_pad")
        registerNormal(112, "nether_bricks")
        registerNormal(113, "nether_brick_fence")
        registerNormal(114, "nether_brick_stairs")
        registerNormal(115, "nether_wart")
        registerNormal(116, "enchanting_table")
        registerNormal(117, "brewing_stand")
        registerNormal(118, "cauldron")
        registerNormal(119, "air") // end portal
        registerNormal(120, "end_portal_frame")
        registerNormal(121, "end_stone")
        registerNormal(122, "dragon_egg")
        registerNormal(123, "redstone_lamp")
        registerNormal(124, "redstone_lamp") // lit redstone lamp
        registerNormal(125, "oak_slab")
        registerComplex(126, 0, "oak_slab")
        registerComplex(126, 1, "spruce_slab")
        registerComplex(126, 2, "birch_slab")
        registerComplex(126, 3, "jungle_slab")
        registerComplex(126, 4, "acacia_slab")
        registerComplex(126, 5, "dark_oak_slab")
        registerNormal(127, "cocoa_beans")
        registerNormal(128, "sandstone_stairs")
        registerNormal(129, "emerald_ore")
        registerNormal(130, "ender_chest")
        registerNormal(131, "tripwire_hook")
        registerNormal(132, "string") // tripwire
        registerNormal(133, "emerald_block")
        registerNormal(134, "spruce_stairs")
        registerNormal(135, "birch_stairs")
        registerNormal(136, "jungle_stairs")
        registerNormal(137, "command_block")
        registerNormal(138, "beacon")
        registerComplex(139, 0, "cobblestone_wall")
        registerComplex(139, 1, "mossy_cobblestone_wall")
        registerNormal(140, "flower_pot")
        registerNormal(141, "carrot")
        registerNormal(142, "potato")
        registerNormal(143, "oak_button")
        registerComplex(144, 0, "skeleton_skull")
        registerComplex(144, 1, "wither_skeleton_skull")
        registerComplex(144, 2, "zombie_head")
        registerComplex(144, 3, "player_head")
        registerComplex(144, 4, "creeper_head")
        registerComplex(144, 5, "dragon_head")
        registerComplex(145, 0, "anvil")
        registerComplex(145, 1, "chipped_anvil")
        registerComplex(145, 2, "damaged_anvil")
        registerNormal(146, "trapped_chest")
        registerNormal(147, "light_weighted_pressure_plate")
        registerNormal(148, "heavy_weighted_pressure_plate")
        registerNormal(149, "comparator")
        registerNormal(150, "comparator") // powered comperator
        registerNormal(151, "daylight_detector")
        registerNormal(152, "redstone_block")
        registerNormal(153, "nether_quartz_ore")
        registerNormal(154, "hopper")
        registerComplex(155, 0, "quartz_block")
        registerComplex(155, 1, "chiseled_quartz_block")
        registerComplex(155, 2, "quartz_pillar")
        registerNormal(156, "quartz_stairs")
        registerNormal(157, "activator_rail")
        registerNormal(158, "dropper")
        registerComplex(159, 0, "white_terracotta")
        registerComplex(159, 1, "orange_terracotta")
        registerComplex(159, 2, "magenta_terracotta")
        registerComplex(159, 3, "light_blue_terracotta")
        registerComplex(159, 4, "yellow_terracotta")
        registerComplex(159, 5, "lime_terracotta")
        registerComplex(159, 6, "pink_terracotta")
        registerComplex(159, 7, "gray_terracotta")
        registerComplex(159, 8, "light_gray_terracotta")
        registerComplex(159, 9, "cyan_terracotta")
        registerComplex(159, 10, "purple_terracotta")
        registerComplex(159, 11, "blue_terracotta")
        registerComplex(159, 12, "brown_terracotta")
        registerComplex(159, 13, "green_terracotta")
        registerComplex(159, 14, "red_terracotta")
        registerComplex(159, 15, "black_terracotta")
        registerComplex(160, 0, "white_stained_glass_pane")
        registerComplex(160, 1, "orange_stained_glass_pane")
        registerComplex(160, 2, "magenta_stained_glass_pane")
        registerComplex(160, 3, "light_blue_stained_glass_pane")
        registerComplex(160, 4, "yellow_stained_glass_pane")
        registerComplex(160, 5, "lime_stained_glass_pane")
        registerComplex(160, 6, "pink_stained_glass_pane")
        registerComplex(160, 7, "gray_stained_glass_pane")
        registerComplex(160, 8, "light_gray_stained_glass_pane")
        registerComplex(160, 9, "cyan_stained_glass_pane")
        registerComplex(160, 10, "purple_stained_glass_pane")
        registerComplex(160, 11, "blue_stained_glass_pane")
        registerComplex(160, 12, "brown_stained_glass_pane")
        registerComplex(160, 13, "green_stained_glass_pane")
        registerComplex(160, 14, "red_stained_glass_pane")
        registerComplex(160, 15, "black_stained_glass_pane")
        registerComplex(161, 0, "acacia_leaves")
        registerComplex(161, 1, "dark_oak_leaves")
        registerComplex(162, 0, "acacia_log")
        registerComplex(162, 1, "dark_oak_log")
        registerNormal(163, "acacia_stairs")
        registerNormal(164, "dark_oak_stairs")
        registerNormal(165, "slime_block")
        registerNormal(166, "barrier")
        registerNormal(167, "iron_trapdoor")
        registerComplex(168, 0, "prismarine")
        registerComplex(168, 1, "prismarine_bricks")
        registerComplex(168, 2, "dark_prismarine")
        registerNormal(169, "sea_lantern")
        registerNormal(170, "hay_block")
        registerComplex(171, 0, "white_carpet")
        registerComplex(171, 1, "orange_carpet")
        registerComplex(171, 2, "magenta_carpet")
        registerComplex(171, 3, "light_blue_carpet")
        registerComplex(171, 4, "yellow_carpet")
        registerComplex(171, 5, "lime_carpet")
        registerComplex(171, 6, "pink_carpet")
        registerComplex(171, 7, "gray_carpet")
        registerComplex(171, 8, "light_gray_carpet")
        registerComplex(171, 9, "cyan_carpet")
        registerComplex(171, 10, "purple_carpet")
        registerComplex(171, 11, "blue_carpet")
        registerComplex(171, 12, "brown_carpet")
        registerComplex(171, 13, "green_carpet")
        registerComplex(171, 14, "red_carpet")
        registerComplex(171, 15, "black_carpet")
        registerNormal(172, "terracotta")
        registerNormal(173, "coal_block")
        registerNormal(174, "packed_ice")
        registerComplex(175, 0, "sunflower")
        registerComplex(175, 1, "lilac")
        registerComplex(175, 2, "tall_grass")
        registerComplex(175, 3, "large_fern")
        registerComplex(175, 4, "rose_bush")
        registerComplex(175, 5, "peony")
        registerNormal(176, "white_banner") // standing banner
        registerNormal(177, "white_banner") // wall banner
        registerNormal(178, "daylight_detector")
        registerComplex(179, 0, "red_sandstone")
        registerComplex(179, 1, "chiseled_red_sandstone")
        registerComplex(179, 2, "cut_red_sandstone")
        registerNormal(180, "red_sandstone_stairs")
        registerComplex(182, 0, "red_sandstone_slab")
        registerNormal(183, "spruce_fence_gate")
        registerNormal(184, "birch_fence_gate")
        registerNormal(185, "jungle_fence_gate")
        registerNormal(186, "dark_oak_fence_gate")
        registerNormal(187, "acacia_fence_gate")
        registerNormal(188, "spruce_fence")
        registerNormal(189, "birch_fence")
        registerNormal(190, "jungle_fence")
        registerNormal(191, "dark_oak_fence")
        registerNormal(192, "acacia_fence")
        registerNormal(256, "iron_shovel")
        registerNormal(257, "iron_pickaxe")
        registerNormal(258, "iron_axe")
        registerNormal(259, "flint_and_steel")
        registerNormal(260, "apple")
        registerNormal(261, "bow")
        registerNormal(262, "arrow")
        registerComplex(263, 0, "coal")
        registerComplex(263, 1, "charcoal")
        registerNormal(264, "diamond")
        registerNormal(265, "iron_ingot")
        registerNormal(266, "gold_ingot")
        registerNormal(267, "iron_sword")
        registerNormal(268, "wooden_sword")
        registerNormal(269, "wooden_shovel")
        registerNormal(270, "wooden_pickaxe")
        registerNormal(271, "wooden_axe")
        registerNormal(272, "stone_sword")
        registerNormal(273, "stone_shovel")
        registerNormal(274, "stone_pickaxe")
        registerNormal(275, "stone_axe")
        registerNormal(276, "diamond_sword")
        registerNormal(277, "diamond_shovel")
        registerNormal(278, "diamond_pickaxe")
        registerNormal(279, "diamond_axe")
        registerNormal(280, "stick")
        registerNormal(281, "bowl")
        registerNormal(282, "mushroom_stew")
        registerNormal(283, "golden_sword")
        registerNormal(284, "golden_shovel")
        registerNormal(285, "golden_pickaxe")
        registerNormal(286, "golden_axe")
        registerNormal(287, "string")
        registerNormal(288, "feather")
        registerNormal(289, "gunpowder")
        registerNormal(290, "wooden_hoe")
        registerNormal(291, "stone_hoe")
        registerNormal(292, "iron_hoe")
        registerNormal(293, "diamond_hoe")
        registerNormal(294, "golden_hoe")
        registerNormal(295, "wheat_seeds")
        registerNormal(296, "wheat")
        registerNormal(297, "bread")
        registerNormal(298, "leather_helmet")
        registerNormal(299, "leather_chestplate")
        registerNormal(300, "leather_leggings")
        registerNormal(301, "leather_boots")
        registerNormal(302, "chainmail_helmet")
        registerNormal(303, "chainmail_chestplate")
        registerNormal(304, "chainmail_leggings")
        registerNormal(305, "chainmail_boots")
        registerNormal(306, "iron_helmet")
        registerNormal(307, "iron_chestplate")
        registerNormal(308, "iron_leggings")
        registerNormal(309, "iron_boots")
        registerNormal(310, "diamond_helmet")
        registerNormal(311, "diamond_chestplate")
        registerNormal(312, "diamond_leggings")
        registerNormal(313, "diamond_boots")
        registerNormal(314, "golden_helmet")
        registerNormal(315, "golden_chestplate")
        registerNormal(316, "golden_leggings")
        registerNormal(317, "golden_boots")
        registerNormal(318, "flint")
        registerNormal(319, "porkchop")
        registerNormal(320, "cooked_porkchop")
        registerNormal(321, "painting")
        registerComplex(322, 0, "golden_apple")
        registerComplex(322, 1, "enchanted_golden_apple")
        registerNormal(323, "oak_sign")
        registerNormal(324, "oak_door")
        registerNormal(325, "bucket")
        registerNormal(326, "water_bucket")
        registerNormal(327, "lava_bucket")
        registerNormal(328, "minecart")
        registerNormal(329, "saddle")
        registerNormal(330, "iron_door")
        registerNormal(331, "redstone")
        registerNormal(332, "snowball")
        registerNormal(333, "oak_boat")
        registerNormal(334, "leather")
        registerNormal(335, "milk_bucket")
        registerNormal(336, "brick")
        registerNormal(337, "clay_ball")
        registerNormal(338, "sugar_cane")
        registerNormal(339, "paper")
        registerNormal(340, "book")
        registerNormal(341, "slime_ball")
        registerNormal(342, "chest_minecart")
        registerNormal(343, "furnace_minecart")
        registerNormal(344, "egg")
        registerNormal(345, "compass")
        registerNormal(346, "fishing_rod")
        registerNormal(347, "clock")
        registerNormal(348, "glowstone_dust")
        registerComplex(349, 0, "cod")
        registerComplex(349, 1, "salmon")
        registerComplex(349, 2, "tropical_fish")
        registerComplex(349, 3, "pufferfish")
        registerComplex(350, 0, "cooked_cod")
        registerComplex(350, 1, "cooked_salmon")
        registerComplex(351, 0, "ink_sac")
        registerComplex(351, 1, "red_dye")
        registerComplex(351, 2, "green_dye")
        registerComplex(351, 3, "cocoa_beans")
        registerComplex(351, 4, "lapis_lazuli")
        registerComplex(351, 5, "purple_dye")
        registerComplex(351, 6, "cyan_dye")
        registerComplex(351, 7, "light_gray_dye")
        registerComplex(351, 8, "gray_dye")
        registerComplex(351, 9, "pink_dye")
        registerComplex(351, 10, "lime_dye")
        registerComplex(351, 11, "yellow_dye")
        registerComplex(351, 12, "light_blue_dye")
        registerComplex(351, 13, "magenta_dye")
        registerComplex(351, 14, "orange_dye")
        registerComplex(351, 15, "bone_meal")
        registerNormal(352, "bone")
        registerNormal(353, "sugar")
        registerNormal(354, "cake")
        registerComplex(26, 0, "white_bed")
        registerComplex(26, 1, "orange_bed")
        registerComplex(26, 2, "magenta_bed")
        registerComplex(26, 3, "light_blue_bed")
        registerComplex(26, 4, "yellow_bed")
        registerComplex(26, 5, "lime_bed")
        registerComplex(26, 6, "pink_bed")
        registerComplex(26, 7, "gray_bed")
        registerComplex(26, 8, "light_gray_bed")
        registerComplex(26, 9, "cyan_bed")
        registerComplex(26, 10, "purple_bed")
        registerComplex(26, 11, "blue_bed")
        registerComplex(26, 12, "brown_bed")
        registerComplex(26, 13, "green_bed")
        registerComplex(26, 14, "red_bed")
        registerComplex(26, 15, "black_bed")
        registerComplex(355, 0, "white_bed")
        registerComplex(355, 1, "orange_bed")
        registerComplex(355, 2, "magenta_bed")
        registerComplex(355, 3, "light_blue_bed")
        registerComplex(355, 4, "yellow_bed")
        registerComplex(355, 5, "lime_bed")
        registerComplex(355, 6, "pink_bed")
        registerComplex(355, 7, "gray_bed")
        registerComplex(355, 8, "light_gray_bed")
        registerComplex(355, 9, "cyan_bed")
        registerComplex(355, 10, "purple_bed")
        registerComplex(355, 11, "blue_bed")
        registerComplex(355, 12, "brown_bed")
        registerComplex(355, 13, "green_bed")
        registerComplex(355, 14, "red_bed")
        registerComplex(355, 15, "black_bed")
        registerNormal(356, "repeater")
        registerNormal(357, "cookie")
        registerNormal(358, "filled_map")
        registerNormal(359, "shears")
        registerNormal(360, "melon_slice")
        registerNormal(361, "pumpkin_seeds")
        registerNormal(362, "melon_seeds")
        registerNormal(363, "beef")
        registerNormal(364, "cooked_beef")
        registerNormal(365, "chicken")
        registerNormal(366, "cooked_chicken")
        registerNormal(367, "rotten_flesh")
        registerNormal(368, "ender_pearl")
        registerNormal(369, "blaze_rod")
        registerNormal(370, "ghast_tear")
        registerNormal(371, "gold_nugget")
        registerNormal(372, "nether_wart")
        registerNormal(373, "potion")
        registerNormal(374, "glass_bottle")
        registerNormal(375, "spider_eye")
        registerNormal(376, "fermented_spider_eye")
        registerNormal(377, "blaze_powder")
        registerNormal(378, "magma_cream")
        registerNormal(379, "brewing_stand")
        registerNormal(380, "cauldron")
        registerNormal(381, "ender_eye")
        registerNormal(382, "glistering_melon_slice")

        registerComplex(383, 65, "bat_spawn_egg")
        registerComplex(383, 61, "blaze_spawn_egg")
        registerComplex(383, 59, "cave_spider_spawn_egg")
        registerComplex(383, 93, "chicken_spawn_egg")
        registerComplex(383, 92, "cow_spawn_egg")
        registerComplex(383, 50, "creeper_spawn_egg")
        registerComplex(383, 63, "ender_dragon_spawn_egg")
        registerComplex(383, 58, "enderman_spawn_egg")
        registerComplex(383, 67, "endermite_spawn_egg")
        registerComplex(383, 56, "ghast_spawn_egg")
        registerComplex(383, 68, "guardian_spawn_egg")
        registerComplex(383, 62, "magma_cube_spawn_egg")
        registerComplex(383, 96, "mooshroom_spawn_egg")
        registerComplex(383, 98, "ocelot_spawn_egg")
        registerComplex(383, 90, "pig_spawn_egg")
        registerComplex(383, 0, "polar_bear_spawn_egg")
        registerComplex(383, 101, "rabbit_spawn_egg")
        registerComplex(383, 91, "sheep_spawn_egg")
        registerComplex(383, 69, "shulker_spawn_egg")
        registerComplex(383, 60, "silverfish_spawn_egg")
        registerComplex(383, 51, "skeleton_spawn_egg")
        registerComplex(383, 55, "slime_spawn_egg")
        registerComplex(383, 52, "spider_spawn_egg")
        registerComplex(383, 94, "squid_spawn_egg")
        registerComplex(383, 120, "villager_spawn_egg")
        registerComplex(383, 66, "witch_spawn_egg")
        registerComplex(383, 64, "wither_spawn_egg")
        registerComplex(383, 95, "wolf_spawn_egg")
        registerComplex(383, 54, "zombie_spawn_egg")
        registerComplex(383, 57, "zombified_piglin_spawn_egg")


        registerNormal(384, "experience_bottle")
        registerNormal(385, "fire_charge")
        registerNormal(386, "writable_book")
        registerNormal(387, "written_book")
        registerNormal(388, "emerald")
        registerNormal(389, "item_frame")
        registerNormal(390, "flower_pot")
        registerNormal(391, "carrot")
        registerNormal(392, "potato")
        registerNormal(393, "baked_potato")
        registerNormal(394, "poisonous_potato")
        registerNormal(395, "map")
        registerNormal(396, "golden_carrot")
        registerComplex(397, 0, "skeleton_skull")
        registerComplex(397, 1, "wither_skeleton_skull")
        registerComplex(397, 2, "zombie_head")
        registerComplex(397, 3, "player_head")
        registerComplex(397, 4, "creeper_head")
        registerComplex(397, 5, "dragon_head")
        registerNormal(398, "carrot_on_a_stick")
        registerNormal(399, "nether_star")
        registerNormal(400, "pumpkin_pie")
        registerNormal(401, "firework_rocket")
        registerNormal(402, "firework_star")
        registerNormal(403, "enchanted_book")
        registerNormal(404, "comparator")
        registerNormal(405, "nether_brick")
        registerNormal(406, "quartz")
        registerNormal(407, "tnt_minecart")
        registerNormal(408, "hopper_minecart")
        registerNormal(409, "prismarine_shard")
        registerNormal(410, "prismarine_crystals")
        registerNormal(411, "rabbit")
        registerNormal(412, "cooked_rabbit")
        registerNormal(413, "rabbit_stew")
        registerNormal(414, "rabbit_foot")
        registerNormal(415, "rabbit_hide")
        registerNormal(416, "armor_stand")
        registerNormal(417, "iron_horse_armor")
        registerNormal(418, "golden_horse_armor")
        registerNormal(419, "diamond_horse_armor")
        registerNormal(420, "lead")
        registerNormal(421, "name_tag")
        registerNormal(422, "command_block_minecart")
        registerNormal(423, "mutton")
        registerNormal(424, "cooked_mutton")
        registerComplex(425, 15, "white_banner")
        registerComplex(425, 14, "orange_banner")
        registerComplex(425, 13, "magenta_banner")
        registerComplex(425, 12, "light_blue_banner")
        registerComplex(425, 11, "yellow_banner")
        registerComplex(425, 10, "lime_banner")
        registerComplex(425, 9, "pink_banner")
        registerComplex(425, 8, "gray_banner")
        registerComplex(425, 7, "light_gray_banner")
        registerComplex(425, 6, "cyan_banner")
        registerComplex(425, 5, "purple_banner")
        registerComplex(425, 4, "blue_banner")
        registerComplex(425, 3, "brown_banner")
        registerComplex(425, 2, "green_banner")
        registerComplex(425, 1, "red_banner")
        registerComplex(425, 0, "black_banner")
        registerNormal(427, "spruce_door")
        registerNormal(428, "birch_door")
        registerNormal(429, "jungle_door")
        registerNormal(430, "acacia_door")
        registerNormal(431, "dark_oak_door")
        registerNormal(2256, "music_disc_13")
        registerNormal(2257, "music_disc_cat")
        registerNormal(2258, "music_disc_blocks")
        registerNormal(2259, "music_disc_chirp")
        registerNormal(2260, "music_disc_far")
        registerNormal(2261, "music_disc_mall")
        registerNormal(2262, "music_disc_mellohi")
        registerNormal(2263, "music_disc_stal")
        registerNormal(2264, "music_disc_strad")
        registerNormal(2265, "music_disc_ward")
        registerNormal(2266, "music_disc_11")
        registerNormal(2267, "music_disc_wait")

        defaultReturnValue(ResourceLocation.withDefaultNamespace("air"))
    }

    private fun Int2ObjectOpenHashMap<ResourceLocation>.put(id: Int, value: String) {
        put(id, ResourceLocation.withDefaultNamespace(value))
    }

    private fun Int2ObjectOpenHashMap<ResourceLocation>.registerNormal(id: Int, nameSpacedId: String) {
        this.put((id).shl(8), nameSpacedId)
    }

    private fun Int2ObjectOpenHashMap<ResourceLocation>.registerComplex(id: Int, damage: Int, nameSpacedId: String) {
        this.put((id).shl(8).or(damage.and(0xFF)), nameSpacedId)
    }

    fun getItem(tag: CompoundTag): Item {
        val id = tag.getIntOrNull("id") ?: throw NullPointerException()
        val shortOr = tag.getShortOr("Damage", 0)
        val resourceLocation = MAP.get(id.shl(8).or(shortOr.toInt().and(0xFF)))?.apply {
            tag.remove("Damage")
        } ?: MAP.get(id.shl(8)) ?: throw NullPointerException("No value found for id $id and damage $shortOr")
        tag.remove("id")
        return BuiltInRegistries.ITEM.getValue(resourceLocation)
    }

}
